export default [
  {
    id: 1,
    postedOn: new Date(),
    title: "Frontend Developer",
    type: "Full time",
    location: "Remote",
    companyName: "Google",
    companyUrl: "https://google.com",
    skills: ["Javascript", "React.js", "Node.js"],
    link: "https://google.com/careers",
  },
  {
    id: 2,
    postedOn: new Date(),
    title: "Backend Developer",
    type: "Part time",
    location: "Office",
    companyName: "Yahoo",
    companyUrl: "https://yahoo.com",
    skills: ["Angular", "Node.js", "Database", "Rest API", "Python"],
    link: "https://yahoo.com/jobs",
  },
  {
    id: 3,
    postedOn: new Date(),
    title: "Mobile Developer",
    type: "Contract",
    location: "Remote",
    companyName: "Facebook",
    companyUrl: "https://facebook.com",
    skills: ["Flutter", "Back-end skills"],
    link: "https://facebook.com/careers",
  },
  {
    id: 4,
    postedOn: new Date(),
    title: "Python Developer",
    type: "Full time",
    location: "Office",
    companyName: "Facebook",
    companyUrl: "https://facebook.com",
    skills: ["Python", "Django", "Rest API"],
    link: "https://facebook.com/careers",
  },
  {
    id: 5,
    postedOn: new Date(),
    title: "Web Developer",
    type: "Contract",
    location: "Office",
    companyName: "Facebook",
    companyUrl: "https://facebook.com",
    skills: ["HTML5", "CSS3", "Javascript", "Responsive Design Principles"],
    link: "https://facebook.com/careers",
  },
];