export default [
  {
    id: 1,
    postedOn: new Date(),
    title: "Frontend Developer",
    type: "Full time",
    location: "Remote",
    companyName: "Google",
    companyUrl: "Google.com",
    skills: ["Javascript", "React.js", "Node.js"],
    link: "https://google.com/careers",
  },
  {
    id: 2,
    postedOn: new Date(),
    title: "Backend Developer",
    type: "Part time",
    location: "Office",
    companyName: "Yahoo",
    companyUrl: "Yahoo.com",
    skills: ["Angular", "node.js","Database","Rest API","python"],
    link: "https://yahoo.com/jobs",
  },
  {
    id: 3,
    postedOn: new Date(),
    title: "MOBILE DEVELOPER",
    type: "Contract",
    location: "Remote",
    companyName: "Facebook",
    companyUrl: "https://facebook.com",
    skills: ["flutter","back-end skills"],
    link: "https://facebook.com/careers",
  },
  {
  id: 4,
  postedOn: new Date(),
  title: "PYTHON DEVELOPER",
  type: "Full time",
  location: "Office",
  companyName: "Facebook",
  companyUrl: "https://facebook.com",
  skills: ["python","Django","Rest API"],
  link: "https://facebook.com/careers",
},
{
  id: 4,
  postedOn: new Date(),
  title: "WEB DEVELOPER",
  type: "Contract",
  location: "Office",
  companyName: "Facebook",
  companyUrl: "https://facebook.com",
  skills: ["HTML5","CSS3","JAVASCRIPT","RESPONSIVE DESIGN PRINCIPLE"],
  link: "https://facebook.com/careers",
},
];
